/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.print.helper.xml -i zcupsmonitor.h -p CupsMonitorInterface
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "CupsMonitorInterface.h"

/*
 * Implementation of interface class ComDeepinPrintHelperInterface
 */

ComDeepinPrintHelperInterface::ComDeepinPrintHelperInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinPrintHelperInterface::~ComDeepinPrintHelperInterface()
{
}

